version: '3.8'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - database.db:/usr/src/app/database.db
